global: 
  applicationName: asset-scraper
  region: us-central1
configurations:
  production:
    configMapData:
      ENABLE_LOGGING: "false"
      PUBSUB_TOPIC: "asset-requests"
      PUBSUB_SUBSCRIPTION: "assetRequestSubs"
  prime:
    configMapData:
      ENABLE_LOGGING: "true"
      PUBSUB_TOPIC: "asset-requests"
      PUBSUB_SUBSCRIPTION: "assetRequestSubs"
  staging:
    configMapData:
      ENABLE_LOGGING: "true"
      PUBSUB_TOPIC: "asset-requests"
      PUBSUB_SUBSCRIPTION: "assetRequestSubs"
replicaCount: 2
revisionHistoryLimit: 1
image:
  repository: gcr.io/g5-images/asset-scraper
  tag: 1.0.0
  pullPolicy: Always
  resources:
    requests:
      memory: 2000Mi
      cpu: 200m
service:
  name: Node
  servicePort: 8085
activeBullSubchart: "memorystore"
memorystore: 
  purpose: bull
  tier: BASIC
  maxmemoryPolicy: allkeys-lfu
  readReplicasMode: READ_REPLICAS_DISABLED
