version: "3"

networks:
  asset-network:
    driver: bridge

services:
  asset-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - asset-network
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PUBSUB_TOPIC=from-asset-scraper
      - PUBSUB_SUBSCRIPTION=to-asset-scraper-sub
      - PROJECT_ID=opex-staging-b877
      - JOB_TIMEOUT=600000
    ports:
      - "8090:8085"

  redis:
    image: redis
    restart: always
    networks:
      - asset-network
    ports:
      - "6379:6379"
