apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{  .Release.Name }}"
  labels:
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
  annotations: 
    reloader.stakater.com/search: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "{{  .Release.Name }}"
      version: "current"
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      labels:
        app: "{{  .Release.Name }}"
        version: "current"
    spec:
      containers:
      - name: "{{  .Chart.Name  }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.servicePort}}
        resources:
          requests:
            cpu: "{{ .Values.image.resources.requests.cpu }}"
            memory: "{{ .Values.image.resources.requests.memory }}"
        env:
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: 1
          - name: MAX_CONCURRENT_JOBS
            value: 2
          - name: ENABLE_LOGGING
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: ENABLE_LOGGING
          - name: PUBSUB_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: PUBSUB_TOPIC
          - name: PUBSUB_SUBSCRIPTION
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: PUBSUB_SUBSCRIPTION
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: {{ include "redis.urlConfigMapName" (list (include "cloud-helper.values.applicationName" $) (get .Values .Values.activeBullSubchart)) }}
                key: {{ include "redis.urlConfigMapKey" . }}
          - name: CLOUDINARY_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: CLOUDINARY_SECRET
          - name: CLOUDINARY_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: CLOUDINARY_KEY
          - name: CLOUDINARY_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: CLOUDINARY_NAME
          - name: CLOUDINARY_TMP_PREFIX
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: CLOUDINARY_TMP_PREFIX
          - name: PORT
            value : "{{ .Values.service.servicePort }}"
        {{- if .Values.image.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.image.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.image.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.image.readinessProbe | indent 10 }}
        {{- end }}
