
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "asset-scraper.gsaName" . }}-storage-object-admin
  labels:
    {{- include "asset-scraper.labels" . | nindent 4 }}
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: {{ include "cloud-helper.values.projectID" $ }}-websites-archives
  role: roles/storage.objectAdmin
  member: serviceAccount:{{ include "asset-scraper.gsaName" . }}@{{ include "cloud-helper.values.projectID" $ }}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "asset-scraper.gsaName" . }}-gscr-admin
  labels:
    {{- include "asset-scraper.labels" . | nindent 4 }}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ include "cloud-helper.values.projectID" $ }}
  role: roles/source.admin
  member: serviceAccount:{{ include "asset-scraper.gsaName" . }}@{{ include "cloud-helper.values.projectID" $ }}.iam.gserviceaccount.com